### ISSUE TITLE
no calories from "get_activities"

### ISSUE THREAD

**Issue by rotti** [hozn/stravalib#100]
Hi Hans,

like posted on https://groups.google.com/forum/#!topic/strava-api/XVs-clWvK7c
there seems to be a bug in 'get_activities'. You dont get "calories" for your activity. 
Within 'get.activity' everything works.

Used version ist 0.6.6

Here is some example code for proving:

```
import os
from stravalib.client import Client

client = Client()
path_for_files = "./config/"


#read my strava access token from file
def read_access_token(file):
    if os.path.exists(path_for_files + file):
        with open(path_for_files + file, 'r') as string_from_file:
            global string
            string = string_from_file.read().replace('\n', '')
            return string
    else:
        sys.exit("...exiting. cannot find " + path_for_files + file)


access_token = read_access_token('access_token')
client.access_token = access_token


for activity in client.get_activities(limit=1):
    strava_id = u'{0.id}'.format(activity)
    print "no calories here"
    print "upload_id:", strava_id
    print "calories:", u'{0.calories}'.format(activity)


activity = client.get_activity(strava_id)
print "\ncalories work here"
print "calories:", activity.calories
```

```
basti ~/git/new master $ pip freeze | grep stravalib
stravalib==0.6.6
basti ~/git/new master $ python calorie_bug.py
no calories here
upload_id: 827202955
calories: None
No handlers could be found for logger "stravalib.model.Activity"

calories work here
calories: 908.9
```

Thanks for your lib once again. Regards

Sebastian

**Comment by rotti** [comment]
also "activity.athlete.lastname" (and some more like firstname; didnt test all though) returns "None", when iterating through "get_activities()" or calling "get_activity()". but "activity.athlete.id" works. not sure if that should work, since there is a "get_athlete()"


```
athlete = client.get_athlete()
athlete_2 = activity.athlete.lastname
#works
print "athlete get_athlete():", athlete.lastname
#doesnt work. Returns "None"
print "athelte get_activity.athlete.lastname", athlete_2
```

Greets 
Sebastian

**Comment by JohnnyLChang** [comment]
Hi Sebastian,

According to official Strava API document, 

Summary representation attributes   
The summary representation of the activity object is the same as the detailed representation, except it does **NOT** include these attributes:
    calories
    description
    gear
    segment_efforts
    splits_metric
    splits_standard
    laps
    best_efforts
    device_name
    embed_token
    photos

**Comment by JohnnyLChang** [comment]
I guess the athlete name is also not included in the protocol.

**Comment by hozn** [comment]
It sounds like this can be closed.  It could be nice in the future if we issued a warning or something if you access attributes that were not fetched (i.e. athlete was populated with summary-level, but you are looking for detail-level attrib).  But then that might just raise a lot of warnings for people that are comfortable with the current "maybe-the-attrib-is-set" behavior.
