### ISSUE TITLE
Request counting?

### ISSUE THREAD

**Issue by loisaidasam** [hozn/stravalib#111]
It would be nice to have some sort of built in request counter (perhaps even in the logging) to keep track of how many API calls an application is making.

I dug around a little bit in the code but couldn't really find anything (maybe it's hiding right in front of my nose!). Is there something like this? Perhaps at the protocol level?

https://github.com/hozn/stravalib/blob/master/stravalib/protocol.py

Maybe this is already achievable by using some sort of a dummy rate limiter?

**Comment by jsamoocha** [comment]
See this on line 178?

```
# TODO: We should parse the response to get the rate limit details and
# update our rate limiter.
# see: http://strava.github.io/api/#access
```
I'm in need of this as well - may work on it in the next weeks or so...

**Comment by loisaidasam** [comment]
Aha, interesting!

**Comment by hozn** [comment]
Yeah, any patches for that would be very welcome!

And @loisaidasam , I think your idea of dummy rate limiter for logging is a great one.  Maybe it would make sense to add a general "hook" concept; I haven't given that a lot of thought.  ... Open to suggestions, PRs, etc.
