### ISSUE TITLE
Inconsistent behavior for activities without laps

### ISSUE THREAD

**Issue by jsamoocha** [hozn/stravalib#112]
See https://github.com/hozn/stravalib/issues/96. Strava is returning a list of laps as part of the response for `get_activity()`. When there are no laps for the activity, the response simply does not have a `laps` property. At the moment of accessing the `laps` property of the `Activity` object without laps (i.e. its `_laps` attribute is `None`), the following code calls Strava and returns a `BatchedResultsIterator` object which is always empty (since there were no laps in the activity in the first place):
```python
@property
def laps(self):
    """
    Iterator of :class:`stravalib.model.ActivityLap` objects for this activity.
    """
    if self._laps is None:
        self.assert_bind_client()
        self._laps = self.bind_client.get_activity_laps(self.id)
    return self._laps
```

Wouldn't it be more appropriate to simply return an empty list in this case?

**Comment by hozn** [comment]
Yeah, I need to review this api. Perhaps the main get-activity didn't
return laps (?) -- but in general I agree. Moreover, we should not have a
dynamic property with same attribute name as the one returned with the
original/parent entity.

**Comment by hozn** [comment]
So, yeah, this was buggy.  It was allowing laps to be set, but it was setting it to a dictionary instead of an `ActivityLap` model.  The behavior now where we just use laps present in the Activity seems better.
