### ISSUE TITLE
Data serialization

### ISSUE THREAD

**Issue by pivancy** [hozn/stravalib#113]
I was really surprised when I was looking through the code and didn't found any serialization (to_json, to_dict, etc.) methods to serialize data somehow.

It was terrible to create some handy serialization for `Activity` model when there are about a 50 fields there and some of them may contain other objects with a huge number of fields.

I guess, this issue is critical enough.

**Comment by hozn** [comment]
If you'd like to submit a pull request that uses the generic model/attribute system to perform to_dict/to_json serialization, that would be welcome.  I can certainly appreciate that this would be useful.  I can look at this at some point too.  Yes, doing it by hand isn't necessary; this should be easy to build programmatically, as the model classes should have all the type information that is needed to serialize to (e.g.) json.  I'd probably just serialize to dict so stravalib doesn't have to concern itself with consumer details like whether decimals should be floats or strings.

**Comment by hozn** [comment]
BTW, there's a `to_dict()` method now.  See #127
