### ISSUE TITLE
Invalid data types

### ISSUE THREAD

**Issue by pivancy** [hozn/stravalib#114]
I'm using `stravalib` for getting updates via web hooks and found one important thing:
Types described in models may be different with types sent in updates.

E.g.:
- `weighted_average_watts` field from `Activity` model has `int` as a data type, but `None` may be sent,
- `description` field from `Activity` model has `six.text_type` as a data type, but `None` may be sent,
...

There is also a lot of these fields.

Why may this be important/critical? I'm trying to validate a data using `trafaret` and found types from the models, but it often fails for `None` types (there may be other issues also, but I've found these once for now).

I guess that data types in models or in responses should be changed according to expected types.

**Comment by hozn** [comment]
So, does the trafaret validator not allow for None?  None isn't really a type in python, so changing our model/attribute types system doesn't really seem to make sense here.  Any of these attributes support `None` values in our model system.  This sounds like a configuration issue in `trafaret` (?)  Or maybe I'm misunderstanding how you're proposing stravalib would address this.

**Comment by pivancy** [comment]
If you'll try to use some basic check it'll also fail:

`isinstance(weighted_average_watts, int)` - fails if weighted_average_watts is None. That's why I don't think that it's a trafaret issue.
Also, if we're talking about saving this data into database, you're not able to save None(empty value), if you defined this field as an int in the database schema.

**Comment by hozn** [comment]
Yeah, that's just how python works; this really is not a stravalib issue.  The type of all the model attributes is implicitly "or None" so your validation library needs to support this.  It looks like this is easy to do in trafaret, though:
```python
(t.Int | t.Null).check(5)
```
From http://trafaret.readthedocs.io/en/latest/intro.html#or
