### ISSUE TITLE
utc_offset deprecated? 

### ISSUE THREAD

**Issue by aligg** [hozn/stravalib#115]
I get a lot of warnings working with the library. I think this is because utc_offset is included in your model but Strava has deprecated that attribute. Do you think that should be changed? I could also try submitting pull request although I haven't done that before!

**Comment by hozn** [comment]
Yeah, we probably need to comment it out, though I also have code that uses that I think -- so I probably need to review what they're doing now instead! :)

**Comment by aligg** [comment]
Cool. Submitted a pull request to try it out.

**Comment by hozn** [comment]
Thanks - merged!  I'll leave this open for now as a reminder to investigate the change from Strava a little more deeply.

**Comment by pcoster** [comment]
Sorry to be a pain. I'm still getting a lot of warnings about the UTC_offset attribute. I've hunted around to try to work it out but no luck. Any advice?

**Comment by hozn** [comment]
@pcoster , I assume you're using the version from pypi?  I need to do a new release.  (No need to apologize; I should have done that sooner.)

**Comment by pcoster** [comment]
Yes I was. Now I get the warnings on python3 but not on python2. I've installed with pip and pip3. Might be embarrassing myself but I though I'd ask anyway. Thanks for building this thing, by the way.

**Comment by hozn** [comment]
I'll do my best to sit down and put together the release this week.  I'd like to take a look at the issues and update changelog, etc.

**Comment by pcoster** [comment]
Cool thanks a lot. Just ignoring the warnings for now seems to be working fine for now. :)

**Comment by hozn** [comment]
This has been fixed.
