### ISSUE TITLE
get_athlete_starred_segments

### ISSUE THREAD

**Issue by wjazdbitu** [hozn/stravalib#117]
In [V3 API](https://strava.github.io/api/v3/segments/#starred) there are methods for collecting authenticated user starred segments and any user starred segments. That second possiblity is missing in stravalib. Code for client.py:
```
    def get_athlete_starred_segments(self, athlete_id, limit=None):
        result_fetcher = functools.partial(self.protocol.get,
                                           '/athletes/{id}/segments/starred',
                                           id=athlete_id)

        return BatchedResultsIterator(entity=model.Segment,
                                      bind_client=self,
                                      result_fetcher=result_fetcher,
                                      limit=limit)
```

The **get_starred_segment** should be **get_starred_segments** by the way.

Could you please add this method to next version?

**Comment by hozn** [comment]
Yeah, that looks pretty straightforward.

**Comment by wjazdbitu** [comment]
Thanks.
