### ISSUE TITLE
get_activity_streams gives 404 error

### ISSUE THREAD

**Issue by pcoster** [hozn/stravalib#118]
When I try to get streams from an activity that doesn't have any streams (A treadmill run in this case) I get a 404 error and the program exits. It seems like a slightly weird situation because there doesn't seem to be a way to check directly from the activity itself whether there are streams, other than to just to fail. 
I'm not sure what the graceful failure would look like here, maybe just catch the exception and return an empty list. Does anyone have any ideas about how to fix this or work around it? Thanks

**Comment by hozn** [comment]
Yeah, I think we'll want to check the response status and explicitly handle 404 for streams.

**Comment by hozn** [comment]
As for a workaround, you could explicitly handle that exception for now. Probably something like:
```python
from requests.exceptions import HTTPError

try:
  streams = client.get_activity_streams(activity_id)
except HTTPError as err:
  if err.response.status_code == 404:
    streams = []
  else:
    raise
```

**Comment by dizhu1991** [comment]
Hi @hozn , I met the same problem now. Because of this error the following parts of my code just can't work. I tried to put in your workaround code, but the error is still there, and another one appeared:
`AttributeError: 'NoneType' object has no attribute 'status_code'`

What can I do now? Thanks.

**Comment by hozn** [comment]
I don't know; I would have to investigate to see what HTTPError is being returned -- and why there's no response object.  I'll look at this when I get a few minutes over some upcoming time off work.

**Comment by hozn** [comment]
This is also a bit related to #134, though I will fix this one more specifically to return empty list.
