### ISSUE TITLE
Warning about "No such attribute from_accepted_tag" from activities

### ISSUE THREAD

**Issue by TorbjornT** [hozn/stravalib#122]
(I guess this is in the same vein as #115, so was unsure whether to add a new issue or not, please just close this one if you like.)

Anyway, when iterating over activities after `get_activities`, I get two warnings for each activity, one about `utc_offset`, the other one is that mentioned in the title:

```
No such attribute utc_offset on entity <Activity id=None name=None resource_state=None>
No such attribute from_accepted_tag on entity <Activity id=N name='Foo' resource_state=2>
```

Where I've removed the actual `Activity id` and `name` for the second one.  Is this second one also a case of deprecated attributes?

I installed with `pip`, so have v0.6.6 as far as I can see. I'm using Python 3.

**Comment by hozn** [comment]
I'm assuming these are either new or deprecated attributes, yes (don't remember exactly under what circumstances it emits that warning).  So, you can ignore the warning for now, but it points to something needed to be cleaned up.  Thanks for reporting.
