### ISSUE TITLE
How to get every attribute of a certain activity

### ISSUE THREAD

**Issue by dizhu1991** [hozn/stravalib#126]
Hi, I am now able to get the list of a certain athlete's activities with get_activities(), and I can print one of several of the attributes (like .id or .start_latlng); however I can't find a way of printing ALL of them or putting them into one data frame, as the number of attributes is so big. get_activity_streams seems doable, but the 11 "types" in get_activity_streams are different from those of activities.

How can I do that?

Thanks.

**Comment by hozn** [comment]
Hi - when you retrieve an athlete's activities with get_activities() you are getting back a list (or an iterator) of `stravalib.model.Activity` objects.  All available attributes are present on that returned object.  See: https://github.com/hozn/stravalib/blob/master/stravalib/model.py#L690

**Comment by dizhu1991** [comment]
Thanks! @hozn Can I ask just one more weak question? How can I transform this class object to something that can be dealt with by pandas? I tried to use activity.__dict__, but it didn't output the values of attributes.

**Comment by hozn** [comment]
Ah, yeah, I think having a `to_dict()` method would be useful.  I'll make a ticket to add that.  Shouldn't be too difficult.
