### ISSUE TITLE
Update stravalib on PyPi?

### ISSUE THREAD

**Issue by sanderroosendaal** [hozn/stravalib#128]
Would be great if we could simply install with pip install - the version on PyPi is somewhat behind what is happening here on github. Thanks

**Comment by hozn** [comment]
Yeah, it is -- I was hoping to add a couple of methods, but I can go ahead and push this out before.  I expect more versions will be coming shortly, as I'm turning to spend some time on development.

**Comment by hozn** [comment]
Ok - 0.7.0 pushed out.  Thanks for the prod!
