### ISSUE TITLE
So many warnings

### ISSUE THREAD

**Issue by dizhu1991** [hozn/stravalib#129]
Hi,

When I call functions from stravalib, there are always so many warnings. For example, when I call get_activities(), there will be an awful lot of warnings like:

No such attribute from_accepted_tag on entity <Activity id=329727250 name='Bayswater' resource_state=2>

Why does this happen? This doesn't affect final results but...

Thanks.

**Comment by hozn** [comment]
@dizhu1991, what version are you using?  Version 0.7.0 should include that attribute.

**Comment by dizhu1991** [comment]
Hi @hozn ,

Thanks! I just updated the latest version. It runs well. 

Cheers,
