### ISSUE TITLE
How to extract segment efforts

### ISSUE THREAD

**Issue by dizhu1991** [hozn/stravalib#132]
Hi @hozn ,

I saw in your documentation that there are functions to extract segment efforts and effort streams if effort id is known. But how to get a list of effort ids during an activity? There doesn't seem to be this function right now. 

Cheers,

Di

**Comment by hozn** [comment]
`Activity.segment_efforts` is a list of `SegmentEffort` objects (https://github.com/hozn/stravalib/blob/master/stravalib/model.py#L700).  (Note that in last-released version this could also be None if it was empty; this has been fixed in master.)

Is that what you're looking for?

**Comment by dizhu1991** [comment]
I'm not so sure... But still, if I want to call `get_segment_effort`, I need to know effort_id, which I don't know where to extract. Is there any way to do that?

**Comment by hozn** [comment]
Right, so from an activity you can get segment efforts, as above. Then the `SegmentEffort.id` attribute gives you the effort ID.   If you need the segment ID, `SegmentEffort.segment.id`.

**Comment by dizhu1991** [comment]
Thanks!

Another question: if the segment efforts are null, it basically means there is no other way of finding them? Or the user didn't upload the data?

**Comment by hozn** [comment]
Yes, if the segment_efforts is `None` this means there were no efforts recorded for the ride.  Perhaps user checked the "exclude from segment leaderboards" option (? - though I'm not sure if this actually removes any efforts from activity), or more likely there just weren't any segments on the route?

The `None` is a bug, which has been fixed, but not released yet.  It should be empty list (`[]`) instead -- and will be in 0.7.1
