### ISSUE TITLE
`get_friend_activities` no longer works

### ISSUE THREAD

**Issue by ColCarroll** [hozn/stravalib#139]
Looks like the endpoint `activities/following` was removed by strava: https://github.com/strava/developers.strava.com/commit/42c85bea6e0f66272015fd8675e0c2535c0c716c#diff-d6222e8ec341b3819cfba9b10f20ce6b

This breaks `stravalib.Client.get_friend_activities`.

Have not dug in to see whether there is a replacement!

**Comment by hozn** [comment]
Yeah, I think this is part of the big, breaking changes Strava just did.

**Comment by hozn** [comment]
https://developers.strava.com/docs/january-2018-update/

**Comment by hozn** [comment]
I don't think there's replacement functionality.  So we probably should remove it from stravalib.

**Comment by hozn** [comment]
I'll address this more comprehensively in #140
