### ISSUE TITLE
Update the "limits" from the rate limit headers in DefaultRateLimiter

### ISSUE THREAD

**Issue by hozn** [hozn/stravalib#141]
Currently the new XRateLimit code updates the usage from the headers, but leaves the limits with whatever they were configured initially.  I think in addition to updating the usage values, it would be appropriate to also update the limits for apps that are using rate limits but might have non-default limits set.

**Comment by jsamoocha** [comment]
`SleepingRateLimitRule` implements this. It updates the short/long limits that are communicated by the Strava API at every response. In addition to using the limits from the response, you can also override them using the `short_limit`, `long_limit` and `force_limits` arguments. Its `__call__` implementation can be used as an example to enable similar behavior in the non-sleeping `XRateLimitRule`.

**Comment by hozn** [comment]
Yeah, I did see that, but felt like it might be more consistent to also update limits from headers here (and not raise exc if the actual limits hadn't been exceeded). I followed same pattern of having the `force_limits` param.

**Comment by hozn** [comment]
Nice work, BTW; this was my first time using the new rate limiters myself!

**Comment by hozn** [comment]
Err, apparently I mistaked my commit.  Fixed in 77fba44e0.
