### ISSUE TITLE
What's going to happen with this library?

### ISSUE THREAD

**Issue by sshevlyagin** [hozn/stravalib#147]
Just noticed that strava significantly revamped their dev story and now you can get an autogenerated swagger library for their API.  @hozn did you know? 
https://github.com/strava/developers.strava.com/#client-code

**Comment by hozn** [comment]
I hadn't seen the codegen code, though I've noticed they've adapted Swagger for their API, yeah.  I guess I'm not sure it really affects this library.

Strava's API is fairly easy to use with the `requests` module already if you want to deal with the low-level.  I think there's value in having higher-level abstractions, and things like the `BatchedResultsIterators` that aren't going to (at least as far as I know) be supported by an autogen codebase.

But I recognize that using an autogen codebase is likely to stay current better!  I'd love to hear from folks that are using an auto-genreated python client and see how the experience compares.
