### ISSUE TITLE
OAuth Updates

### ISSUE THREAD

**Issue by jsamoocha** [hozn/stravalib#162]
See [Strava's message](https://developers.strava.com/docs/oauth-updates/) about the replacement of permanent access tokens by short-lived ones. This may require some thoughts about redesigning the API...

**Comment by ghn** [comment]
Hi! any plan for this update yet?

**Comment by hozn** [comment]
PRs welcome. I haven't had time to look at this yet, no.

**Comment by hozn** [comment]
Released in 0.10.0 -- thanks @david-pacheco

**Comment by david-pacheco** [comment]
I realized there is an issue with my solution. Apparently Strava is not returning the refresh token on the first authentication if the correct "scopes" are not passed in the initial authorization request (according to this post: https://stackoverflow.com/questions/53009519/strava-api-refresh-token-doesnt-issued-after-first-authorization). So the authorize_url method must also be changed...
