### ISSUE TITLE
The current 'authorize_url' method is not compatible with new Strava OAuth

### ISSUE THREAD

**Issue by david-pacheco** [hozn/stravalib#164]
After the release of 0.10.0, the new Strava OAuth is not fully functional if the scopes for the authorize_url are not updated. (https://stackoverflow.com/questions/53009519/strava-api-refresh-token-doesnt-issued-after-first-authorization)

**Comment by hozn** [comment]
Thanks for following up with this.  I should have checked w/ you before pushing out that release.  Clearly I'm not actively using stravalib or I probably would have caught this.

**Comment by hozn** [comment]
(Pushed out in 0.10.1)
