### ISSUE TITLE
0.10.1 still doesn't have right scopes in protocol

### ISSUE THREAD

**Issue by glandais** [hozn/stravalib#168]
Scopes are available here : https://developers.strava.com/docs/authentication/

Also, scope is multivalued, the assertion will fail if we try to use several scopes.

**Comment by alistair0adams** [comment]
Yep, that the problem I just encountered. I just commented out the assert for now.

**Comment by hozn** [comment]
I will review this and get this more properly fixed -- hopefully tonight.
Apologies, all.

**Comment by hozn** [comment]
This should be fixed now, but let me know what you find next.

**Comment by alistair0adams** [comment]
I noticed after I commented that there's a pending pull request to fix this which does it in a slightly different way. Both look good to me.
