### ISSUE TITLE
get_athlete fails with 'The /athletes/{id} endpoint was removed by Strava'

### ISSUE THREAD

**Issue by shenki** [hozn/stravalib#172]
```python
In [17]: a = client.get_athlete(<num>)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-17-968412ea03f1> in <module>()
----> 1 steve = client.get_athlete(<num>)

/home/joel/dev/strava/.venv/lib/python3.6/site-packages/stravalib/client.py in get_athlete(self, athlete_id)
    235             raw = self.protocol.get('/athlete')
    236         else:
--> 237             raise NotImplementedError("The /athletes/{id} endpoint was removed by Strava.  "
    238                                       "See https://developers.strava.com/docs/january-2018-update/")
````

**Comment by shenki** [comment]
I am using 0.10.2

**Comment by shenki** [comment]
I notice now that this is stravalib returning this error, not the API as I initially thought.

Does this mean strava doesn't support requesting other users data?

When I'm logged in as myself, I can see the user I'm trying to request. This means I can scrape it from the browser, but is there an API for this?

**Comment by jsamoocha** [comment]
Strava _does_ support requesting other users data. You'll need these users' access tokens, however.

**Comment by hozn** [comment]
Yes, correct. You can only request the profile for the authorized / "logged in" athlete.

**Comment by shenki** [comment]
Thanks for clarifying. It's confusing that Strava exposes much less data via the API than they do via the web interface.

I guess I will go back to scraping the website.
