### ISSUE TITLE
activity.description always returns None

### ISSUE THREAD

**Issue by ayi092** [hozn/stravalib#178]
I am able to get all attributes of an activity with the exception of its description. No error is thrown, but it returns None every time even though I have descriptions in the activity.

`import stravalib

def get_activities(limit: int) -> stravalib.client.BatchedResultsIterator:
    """
    """
    client = stravalib.client.Client(access_token='XXXXXXXXXXX')
    client.get_athlete()
    activities = client.get_activities(limit=limit)
    return activities

def print_activities(acts: stravalib.client.BatchedResultsIterator) -> None:
    """
    """
    for act in acts:
        print(act.description)
    return

def main():
    acts = get_activities(10)
    print_activities(acts)

if __name__ == '__main__':
    main()`

**Comment by maartenmennes** [comment]
I reported the same problem almost a year ago #142 

I would like to use it to better track different gear (likes different wheels used on the same bike).

**Comment by alasspri** [comment]
This looks like it is a bit of an odd quirk of the Strava API.

**GET** `/activities` returns with a resource state of `2`, which is summary details, but there is no description field returned in this response. This is the endpoint called by the `get_activities()` function.

**GET** `/activities/{id}` returns with a resource state of `3`, which is full details and does include the description field. So you should be able to iterate through all of the activities returned by `get_activities()` and then run `get_activity()` using the id as you iterate through. This will then let you access the description field.

https://github.com/hozn/stravalib/blob/5500ebc39e0bf4706bb1ca4c27b25e56becaaa5f/stravalib/client.py#L492

**Comment by ayi092** [comment]
@alasspri 
Fantastic. That will work just fine. Thanks for pointing that out.
