### ISSUE TITLE
API update has broken stuff

### ISSUE THREAD

**Issue by robross74** [hozn/stravalib#179]
Hi,

Looks like the API update on 17th Jan has broken quite a bit on functionality?  Lots of these sorts of errors from previously working code:

NotImplementedError: The /athletes/{id} endpoint was removed by Strava.  See https://developers.strava.com/docs/january-2018-update/

Happy to test proposed fixes but not really at a level to contribute to the repairs themselves.

Rob

**Comment by hozn** [comment]
Yes, this functionality no longer exists; that is why the code now raises a `NotImplementedError` with a link to the original announcement.  I can't really make Strava bring that functionality back :)

**Comment by hozn** [comment]
Yeah, they made a lot of developers angry when they pulled out support for
querying athletes, etc.  From a privacy perspective what they did makes
sense .... but it was sudden and swift and removed a lot of functionality
that used to exist.
