### ISSUE TITLE
GetStreams for activity type "Run" not returning watts

### ISSUE THREAD

**Issue by ethanopp** [hozn/stravalib#187]
I'm aware strava does not currently display watts for Runs on their website, but it seems that they do still consume the data by users using a run power meter (i.e. Stryd).

3rd party extensions like Elevate can see this power data, however when trying to pull with the api, watts are not returned.

Here is an example where Elevate can see the power data, however when pulling with the following code, 'watts' are not returned:
https://www.strava.com/activities/2642896430#

```
client = get_strava_client()
types = ['time', 'latlng', 'distance', 'altitude', 'velocity_smooth', 'heartrate', 'cadence', 'watts', 'temp', 'moving', 'grade_smooth']
streams = GetStreams(client, 2642896430, types)
print(streams.keys())
```
returns:
`dict_keys(['altitude', 'latlng', 'velocity_smooth', 'cadence', 'grade_smooth', 'heartrate', 'temp', 'distance', 'moving', 'time'])`

**Comment by jsamoocha** [comment]
I think this question should be for Strava (or Stryd) since it's Strava that is not returning the watts stream.

From my experience, the API's behavior is sketchy. For some users, running power is returned, for others, it's not. It may depend on the device they used, or how these activities were uploaded to Strava.

**Comment by ethanopp** [comment]
Ah well that’s unfortunate...wanted to make sure it wasn’t this library restricting the types before going to strava support - because there’s nothing in their documentation that would indicate watts shouldn’t be returned... submitted a ticket to strava support to see what they say

**Comment by ethanopp** [comment]
Also spoke with stryd and they said if using Apple Watch (which I do) watts should come thru the API but not if using garmin...not exactly sure why though...if anyone has an Apple Watch stryd .fit file I’d be happy to test it...otherwise have to wait for mine to come in the mail around the end of September

**Comment by montant** [comment]
If it helps to figure out which configuration works and which doesn't: I'm
owner of a Suunto Spartan and a Stryd sensor, and I have watts data
available on Strava Website.

Joël

**Comment by ethanopp** [comment]
Would you mind sharing a .fit file so I can test the API on it?

**Comment by montant** [comment]
Here is a .fit file as exported from Suunto App (from Strava, I found how
to export as GPX, but not as FIT).

Notice I was not fully correct when I wrote "power data is available on
Strava website". In fact I don't see power data on _website_, but I'm
seeing them on _Strava android app_ (thus Strava is getting them anyway).

Joël

**Comment by ethanopp** [comment]
@montant Doesn't look like anything was attached? Also the main strava website would not show the power data, but if you had an extension like Elevate installed for google chrome or firefox I would think you should be able to see it

**Comment by montant** [comment]
@ethanopp 
Hopefully the file should be here now:
[TrailRunning_2019-08-24T08_01_17.zip](https://github.com/hozn/stravalib/files/3537459/TrailRunning_2019-08-24T08_01_17.zip)

Thanks for the tip about elevate, it is installed now, and "digesting" my history of moves.

**Comment by ethanopp** [comment]
@montant Thanks for the file!

Just confirmed that strava API is now returning watts, going to close this... Seems like its just an issue with the Garmin created .fit files
