### ISSUE TITLE
get_activity_streams not returning all data points

### ISSUE THREAD

**Issue by ethanopp** [hozn/stravalib#188]
Title says it all... API does not seem to be returning all data points of the activity...

```
def GetStreams(client, activity, types):
    streams = client.get_activity_streams(activity, types=types)
    return streams

streams = GetStreams(client, 2727540083, types)
```

Instead of starting from time=0 (or 1), the first data point is over 3 minutes into the workout (i.e. time=second 184).

When exporting the TCX directly from the activity page on strava, all data points get downloaded.

**Comment by jsamoocha** [comment]
Do these first 184 seconds happen to be within the athlete's privacy zone? If so, do you have an access token with sufficient scope for reading private activities?

**Comment by ethanopp** [comment]
Ah didn’t even think of this! Yes they were in the privacy zone...what scope do I need to request for this?

It’s just my own personal app, so which scope can I use for all access? I thought what I am currently using would do it:

scope=['activity:write', 'activity:read', 'profile:write'])

**Comment by 35944** [comment]
These are your options:

'read', 'read_all', 'profile:read_all', 'profile:write', 'profile:write',
'activity:read', 'activity:read_all', 'activity:write'

You’ll need activity:read_all for this one

Op za 21 sep. 2019 om 22:01 schreef ethanopp <notifications@github.com>

**Comment by ethanopp** [comment]
That did it! Thanks
