### ISSUE TITLE
How to get activity stream into a usable form.

### ISSUE THREAD

**Issue by ChrisRSA** [hozn/stravalib#192]
Hi there, really enjoying using stravalib.

I was just wondering if you could help me get data from activity stream into a usable form such as pandas data frame?

I have used your code as follows:
```
# Activities can have many streams, you can request desired stream types
types = ['time', 'latlng', 'altitude', 'heartrate', 'temp', ]

streams = client.get_activity_streams(123, types=types, resolution='medium')

#  Result is a dictionary object.  The dict's key are the stream type.
if 'altitude' in streams.keys():
    print(streams['altitude'].data)
```

This is what I am attempting and the output I get.

```
x = pd.DataFrame.from_dict(streams, orient='index')
print(x)

                                                           0
altitude   <Stream type=altitude resolution=medium origin...
latlng     <Stream type=latlng resolution=medium original...
heartrate  <Stream type=heartrate resolution=medium origi...
distance   <Stream type=distance resolution=medium origin...
time       <Stream type=time resolution=medium original_s...
```

**Comment by jsamoocha** [comment]
You need to create your DataFrame columns from the stream's `data` attribute. One way to achieve that is by using a dict comprehension in your DataFrame constructor, e.g.:

```
streams = client.get_activity_streams(
    123,
    types=['time', 'latlng', 'altitude', 'heartrate', 'temp', ]
)

stream_df = pd.DataFrame(
    {stream_type: streams[stream_type].data for stream_type in streams},
    index=streams['time'].data
)
```

Notice that every element in your `streams` dictionary is an object of type `Stream`. Pandas does not automagically know how to interpret these objects and as such `from_dict()` doesn't work.

**Comment by ChrisRSA** [comment]
Thank you so much! That worked. I cant tell you how frustrated I have been trying to work that out.
