### ISSUE TITLE
Effort count alternative ? 

### ISSUE THREAD

**Issue by latusaki** [hozn/stravalib#193]
I have posted this to strava api group with no response, so here goes..
I am using this library to keep track of the number of users for some segments. I have been doing this using the segment leaderboard effort count. With that functionality being removed, is there any way of getting this information? I don't care about anything other than how many users completed the segment "today". If not by segments are there any alternatives? Looking at the docs seems I'm out of luck.

**Comment by tnikkel** [comment]
The get_segment call should return a segment object with an effort_count field. If you call that once every day at the same time you can subtract todays value from yesterdays value to get the number of efforts recorded in the last 24 hours.

**Comment by latusaki** [comment]
I am looking at general segment usage, not for a specific athlete.

**Comment by tnikkel** [comment]
If you look at https://developers.strava.com/docs/reference/#api-Segments-getSegmentById it has:

  "effort_count" : 309974,
  "athlete_count" : 30623,
  "star_count" : 2428,
  "athlete_segment_stats" : {
    "pr_elapsed_time" : 553,
    "pr_date" : "1993-04-03",
    "effort_count" : 2
  }

The effort_count outside of athlete_segment_stats seems like it should track effort count of all athletes. Does it not?

**Comment by latusaki** [comment]
Sounds like you are right, currently I am using this : '''
Leaderboard = client.get_segment_leaderboard(segment_id, timeframe=TIMEFRAME[timeframe])
 leaderboard.effort_count
'''
The count you shared sounds like all-time, but should be easy enough to calculate daily. Thanks!
