### ISSUE TITLE
Strava API change for activities without GPS lead to deserialization error

### ISSUE THREAD

**Issue by jsamoocha** [hozn/stravalib#215]
It seems there was an (as far as this moment) unannounced API change in Strava where activities without GPS are now returned with `[]` as the value of the `start_latlng` attribute. I don't know what value was returned before, but now the following snippet in `attributes.py` fails with an `IndexError`:

```
    def unmarshal(self, v):
        """
        """
        if not isinstance(v, LatLon):
            v = LatLon(lat=v[0], lon=v[1])
        return v
```

**Comment by slackorama** [comment]
Got burned by this today. Thanks for working on a fix.

I vote for `None`

**Comment by TheBeakerton** [comment]
Same, also found this "surprise" today.  `None `makes sense to me.  Thank you!

**Comment by pgp80** [comment]
Got this one beginning yesterday, for me it's when I'm pulling a list of strava activities based on a predetermined date selector in my django web app, definitely would appreciate a fix if someone can do it!

**Comment by yvetterowe** [comment]
Same here, thanks for fixing this!

**Comment by hozn** [comment]
I pushed out 0.10.3. I'm having some issues with my API App, so having a hard time validating.  (it's saturated its quotas; I need to talk to the freezingsaddles folks about setting up their own API App). Please let me know if there are any issues with this new release.

**Comment by yvetterowe** [comment]
> I pushed out 0.10.3. I'm having some issues with my API App, so having a hard time validating. (it's saturated its quotas; I need to talk to the freezingsaddles folks about setting up their own API App). Please let me know if there are any issues with this new release.

Thank you for the new release! I bumped the version in my app but hit https://github.com/hozn/stravalib/issues/217 - happy to open a PR to fix it if it makes sense.

**Comment by hozn** [comment]
Thanks again for checking my work.  I need to start a conversation w/ Strava about some sort of test account for functional testing this library to unblock my sharing an actual live application for testing.
