### ISSUE TITLE
Incorrect documentation for authorizing client to read private activities

### ISSUE THREAD

**Issue by samryan18** [hozn/stravalib#219]
[Incorrect documentation](https://pythonhosted.org/stravalib/api.html#stravalib.client.Client.authorization_url):
![image](https://user-images.githubusercontent.com/23075262/132715846-fc70dd3e-7ecf-4b86-9473-ab480532640e.png)

Source code with valid scope params:
https://github.com/hozn/stravalib/blob/eabeabf5b40d818ea7c0d9f0bd6c4d619450581f/stravalib/protocol.py#L83-L88

**Comment by samryan18** [comment]
Need to take a look at how these docs were generated. Can give this a go soon

**Comment by lwasser** [comment]
oh interesting - i think that is the API docs via [Sphinx autodoc](https://github.com/hozn/stravalib/blob/master/docs/conf.py#L32)

The code actually looks correct here.

https://github.com/hozn/stravalib/blob/eabeabf5b40d818ea7c0d9f0bd6c4d619450581f/stravalib/protocol.py#L66

@hozn how are you building your docs? it doesn't look like you are using read the docs but i could be wrong. I am happy to update the contributing documentation to help folks contribute if that is useful and if the docs get a fresh push this issue may be resolved as the doc string may be correct? @samryan18 does it look correct to you ? <the link above that i posted?>. 

we could potentially setup an auto build too if that is useful using either [read the docs](https://readthedocs.org/) or github actions.

**Comment by hozn** [comment]
Docs were generated using [sphinx](https://www.sphinx-doc.org/en/master/); however, I suspect the system used has been deprecated, etc.  So would welcome anyone wanting to rethink how those are built etc.  There is a `Makefile` which looks like it was auto-creatd by sphinx in the `doc` directory.  So `make html` may just work .... but as to how those were uploaded, etc. that I suspect has not aged well.

Auto-generating these would be fantastic and certainly was on the list of things to do, but just hasn't been done.

**Comment by lwasser** [comment]
@hozn great! i'm happy to help with this. I will open a new issue and we can talk through there what you prefer in terms of infrastructure. then I will implement and update the contributing section of the readme accordingly via a PR. More over the next day or two.

**Comment by hozn** [comment]
Thanks so much!  I appreciate the help.

**Comment by lwasser** [comment]
hey @samryan18 ! i did a documentation update in the fall - the new docs are here: 
https://stravalib.readthedocs.io/en/latest/

are you able to check for me to see if the documentation looks correct to you now? if it does we can likely close this issue! the docs are now building directly from the docstring code when we merge PR's.

**Comment by samryan18** [comment]
@lwasser the API documentation referenced at the top of the issue appears to be resolved!

p.s. the docs look much nicer now :)

**Comment by lwasser** [comment]
wonderful!! Thanks so much @samryan18 !! and glad you like the n ew docs. also sorry i missed this back in april when you replied yikes!!
