### ISSUE TITLE
A few new issues with strava data access - get_athlete() returning Unable to set attribute nickname on entity... (seems to not like shoes) :)

### ISSUE THREAD

**Issue by lwasser** [hozn/stravalib#220]
Hey y'all.
i'm running into issues with code that used to work. i'm open to helping (i see that the maintainer would like some help and i get that burden of maintaining a package like this that people use!) but need a bit of guidance to understand what's going wrong. I authenticate and such and all works well. Then i try to get my current profile:

```
client.get_athlete()
```

it works and correctly returns  my name but also returns a much longer version of this warning (ALL of my shoes both retired and current):
```
Unable to set attribute nickname on entity <Shoe id=g3735826 name='La Sportiva Lycans'>
Unable to set attribute retired on entity <Shoe id=g3735826 name='La Sportiva Lycans' resource_state=2>
Unable to set attribute converted_distance on entity <Shoe id=g3735826 name='La Sportiva Lycans' resource_state=2>
Unable to set attribute nickname on entity <Shoe id=g6665238 name='La Sportiva red bushidos'>
```

i see the log warning [being thrown here](https://github.com/hozn/stravalib/blob/master/stravalib/attributes.py#L361) i think?

Is anyone else finding this issue? did Strava make some changes to their API as this code used to work - i was using it a month ago. I just updated to the newest version of stravalib (thank you maintainers for pushing this to pypi!)

I'm also running into issues with accessing my activities that i didn't use to have but i'll save that for a separate issue. if i can help i'd love to start with something small to get to know the package and such. thank you in advance

i'm working on python 3.9.2 but created another envt with python 3.8.10 and get the same issue. thanks for any feedback and direction.

**Comment by hozn** [comment]
Yeah, this sounds like Strava updating the attributes in their entities. If I can find a spare minute, I can look up the new attrs in their API and add them, but also happy to take any PR to do that.

**Comment by lwasser** [comment]
hey @hozn thanks for the speedy response. 

if you can provide a bit of direction i can try to help but i did find this in the api:
https://developers.strava.com/docs/reference/#api-Athletes-getLoggedInAthlete

```
{
  "id" : 1234567890987654321,
  "username" : "marianne_t",
  "resource_state" : 3,
  "firstname" : "Marianne",
  "lastname" : "Teutenberg",
  "city" : "San Francisco",
  "state" : "CA",
  "country" : "US",
  "sex" : "F",
  "premium" : true,
  "created_at" : "2017-11-14T02:30:05Z",
  "updated_at" : "2018-02-06T19:32:20Z",
  "badge_type_id" : 4,
  "profile_medium" : "https://xxxxxx.cloudfront.net/pictures/athletes/123456789/123456789/2/medium.jpg",
  "profile" : "https://xxxxx.cloudfront.net/pictures/athletes/123456789/123456789/2/large.jpg",
  "friend" : null,
  "follower" : null,
  "follower_count" : 5,
  "friend_count" : 5,
  "mutual_friend_count" : 0,
  "athlete_type" : 1,
  "date_preference" : "%m/%d/%Y",
  "measurement_preference" : "feet",
  "clubs" : [ ],
  "ftp" : null,
  "weight" : 0,
  "bikes" : [ {
    "id" : "b12345678987655",
    "primary" : true,
    "name" : "EMC",
    "resource_state" : 2,
    "distance" : 0
  } ],
  "shoes" : [ {
    "id" : "g12345678987655",
    "primary" : true,
    "name" : "adidas",
    "resource_state" : 2,
    "distance" : 4904
  } ]
}
```

then i found the summary for gear:
https://developers.strava.com/docs/reference/#api-models-SummaryGear

<img width="585" alt="Screen Shot 2021-09-09 at 7 29 19 PM" src="https://user-images.githubusercontent.com/7649194/132784175-a2c10cee-c660-469b-9bb0-e1df38e40f31.png">


also it's weird because when i convert the athlete response to a dict i see my shoes there.
[i'm looking here at the model.Athlete class](https://github.com/hozn/stravalib/blob/master/stravalib/model.py#L277)

i will attempt to create a dev envt locally but it will likely take me some time to figure out the class structure and the api structure. if you want to give me a bit of direction i'm happy to try to help as much as i can as well. If it's a quick fix for someone else i can look at it while i'm figuring out the structure in hopes that i can help more in the future.

**Comment by yihong0618** [comment]
@lwasser will also give a try~

**Comment by yihong0618** [comment]
@lwasser @hozn 

You can just add the Attribute on Shoe model. like below.

![image](https://user-images.githubusercontent.com/15976103/132798425-97438d6c-d7e1-4c02-915b-685859df9b89.png)

I can provide a `PR` or you continue as this?

**Comment by lwasser** [comment]
@yihong0618 please go ahead and give it a try! i will see how you do it. i see now the Shoe object is going to grab the structure from Gear. i got a bit confused because shoe was empty and gear seemed to have attributes for shoes.

I am happy to test your PR if you want to submit. i haven't had a chance to set up the dev envt yet and am still wrapping my head around the hierarchy of the class structure.

**Comment by hozn** [comment]
Thank you both for taking a stab at this.

**Comment by lwasser** [comment]
Hey @yihong0618 @hozn that fix worked!! Code below - i added retired as that is being thrown as a warning for me too.

@yihong0618 curious - i'm digging through the API and don't actually see where those attributes are stored - i took a wild guess that retired would be a boolean and it worked but i was just curious if you looked at their docs or just looked at the error and identified a few attributes that were missing - nickname, distance and retired. 

This is what i added (pretty much your code plus the `retired` attribute which i had to guess about):

```python
class Shoe(Gear):
    """
    Represents an athlete's pair of shoes.
    """
    nickname = Attribute(six.text_type, (DETAILED,))  #: Nickname for the shoe.
    converted_distance = Attribute(float, (SUMMARY, DETAILED), units=uh.meters) # Distance on the shoe (meters)
    retired = Attribute(bool, (SUMMARY, DETAILED))
```

**Comment by lwasser** [comment]
so @yihong0618 i'm happy to submit a PR or you can either way it gets fixed!! i'll post my second error that may be a pagination issue in just a bit.

**Comment by yihong0618** [comment]
> so @yihong0618 i'm happy to submit a PR or you can either way it gets fixed!! i'll post my second error that may be a pagination issue in just a bit. 

Cool，Submit the PR.
I think the api doc from strava did not update. I just do some test and some guess and found the problem.

**Comment by yihong0618** [comment]
> ok @yihong0618 submitting now. That's helpful that you weren't able to find this in the docs too as i wasn't sure if i was looking in the wrong place! 

My pleasure.
