### ISSUE TITLE
Update Documentation Infrastructure for Stravalib

### ISSUE THREAD

**Issue by lwasser** [hozn/stravalib#222]
In issue #219 , @samryan18 points out that the documentation is out of date. This is likely because the python hosted service doesn't seem to be operating as it used to operate currently. The docs here are already using sphinx which makes it super easy to port to a new platform quickly! We have two options. 

## [Read the Docs](https://readthedocs.org/): 

This platform will automagically connect to a github repo with sphinx setup and allow you to build documentation. it supports versioning, custom environments and branch development of documentation if needed. 

### Potential Drawbacks:
   * maintainers need to setup an account (you can use github to login) 
   *  if docs are failing sometimes you will have to fix things within read the docs (this is rare but i have to do it maybe once or twice a year for our packages). 
   * Advertisements on the docs - see examples below:
[Earthpy docs using standards sphinx theme](https://earthpy.readthedocs.io/en/latest/) 
[Geopandas docs using read the docs (pydata theme)](https://geopandas.readthedocs.io/en/latest/docs.html )
[GEOPANDAS docs running on gh pages - note the lack of versions at the bottom but also no ads: ](https://geopandas.org/index.html)
   * i've run into memory issues with some dev environments using RTD especially if you use conda

What i like to do with this build is create a local github action that tests the documentation build. often you can see the point of error and correct it in github without even having to touch read the docs. every once in a while you need to go into the read the docs admin interface. the new url for docs would be: stravalib.readthedocs.io 

### Benefits
* Doc build maintained by RTD platform
* All versions of your package documentation including latest available to users
* will be super fast to get up and running

##  2. Github Pages Build
In this scenario we'd build the docs via github actions and push them to a new branch here called gh-pages. We'd turn on github pages on the repo and the new docs url will be stravalib.github.io/ . This could work as well but the onus would be on stravalib maintainers to maintain the sphinx website. it would be a bit more infrastructure development here as well to maintain. This solution would also not provide versioned docs so it would always be "latest". Read the docs keeps that history online which is nice. On the flip side in this scenario no one needs a separate set of permissions to work on doc build issues. So in the long term it could be easier if you want more people to be able to help update builds, docs etc.

### Drawbacks
  * A bit more work up front to setup CI infrastructure for the build (but probably worth it)
  * No versioned built docs available to the user online
 
### Benefits
  * No need for an additional login as it all lives here in github / github pages
  * Easier for anyone to update doc builds and such without need special permissions to authenticate with RTD
  * Because the build happens here it's easier to control the envt and avoid envt issues that you can get with RTD
  * no advertisements on your docs

Gosh, now that i typed this all out i am wondering if a github pages build will be easier for long term maintenance because anyone could fix builds without needing permission to use RTD. @hozn do you have any thoughts on this? i'm happy to work on either option.

**Comment by yihong0618** [comment]
Cool.

**Comment by hozn** [comment]
@lwasser , wow - thank you for putting the time into writing this up.  I agree that after reading this the github pages sounds very strong. If you're willing to help make it happen, I'm happy to help support however I can.  Happy to give you project maintainer perms, etc. assuming that may be necessary to setup CI.  I really appreciate the help!

(I'm also 100% cool with a readthedocs-based solution; that is certainly a known quantity too.)

**Comment by yihong0618** [comment]
@hozn 
I can do some help about the code side.

**Comment by hozn** [comment]
@yihong, thank you!

**Comment by lwasser** [comment]
awesome!! @hozn @yihong0618 great!! i'll work on pulling together the actions for and we can go from there! @yihong0618  you rock! i'll ping you when i have a draft for review or when i see areas that I may need help. @hozn i will need permissions to setup secrets in the repo to push. But let me test this out on my fork first and I will followup!

**Comment by lwasser** [comment]
heya @hozn @yihong0618 the deployment to gh pages is actually easier than i thought. [Want to check out a prototype?](https://www.leahwasser.com/stravalib ) I have a domain set to my account but obviously we would host the final docs at hozn.github.io/stravalib . This is just for testing. 

I have the docs building via a github action and then they push to gh-pages when we want them to - id assume we'd want to do this on a commit to master. 

I have a few things to work on including 
- [ ] a ton of broken links to the old version of the API
- [ ] docstring fixes

My one question now is are you committed to the param / type approach to doc strings? I ask because i'm getting some warnings right now that may or may not be related to this BUT also, if we used numpy style docstrings they'd be a bit easier to read i think. This is my opinion so i dont want to push this on anyone. 

## Example - Current documentation style
```python
    def __init__(self,
                 access_token=None,
                 rate_limit_requests=True,
                 rate_limiter=None,
                 requests_session=None):
        """
        Initialize a new client object.

        :param access_token: The token that provides access to a specific Strava account.  If empty, assume that this
                             account is not yet authenticated.
        :type access_token: str
```

## Numpy Style

```python
    def __init__(self,
                 access_token=None,
                 rate_limit_requests=True,
                 rate_limiter=None,
                 requests_session=None):
        """
        Initialize a new client object.

        Parameters
        -------------
        access_token : str 
               The token that provides access to a specific Strava account.  If empty, assume that this
                account is not yet authenticated.
```
Numpy requires less text in the docstring and i think that makes it also a bit easier to maintain. 
Let me know what you think and if you have any other issues / questions about the docs i'm happy to discuss!

Once this is all setup and everyone is happy i'll update the contributing guide and the readme and will submit a PR!

**Comment by hozn** [comment]
@lwasser , as you're doing the work here, I'm happy to convert to your preferred docstring style.  I use this (the current) doc style generally, as it works well in IDEs like PyCharm, but if the numpy docs do as well, I agree they look like their made with humans in mind instead of just computers.

The prototype looks awesome.  Well done.

**Comment by yihong0618** [comment]
@lwasser both styles seems fine.
