### ISSUE TITLE
get_activities giving errors

### ISSUE THREAD

**Issue by greenpasta** [hozn/stravalib#41]
When I use get_activities (in latest github version) I get errors such as the following:

Unable to set attribute achievements on entity \<SegmentEffort id=5525265906 name='Longfellow Loop - No cul-de-sac' resource_state=2>
No such attribute similar_activities on entity \<Activity id=None name='Easy with H+P in Old Beechwood' resource_state=3>

Despite these errors, it otherwise works fine.

**Comment by hozn** [comment]
I noticed that too, will push a fix.

**Comment by hozn** [comment]
The similar_activities issue fixed in f15c963

**Comment by hozn** [comment]
Looks like the achievements is a new Strava structure (undocumented) that
is related to the new "current year" trophies. I need to sign up a few more
examples. Also, I will probably suppress those warnings (lower to emit only
in debug mode or something), as it is clear that Strava is always going to
be pushing undocumented features into the API.

**Comment by greenpasta** [comment]
I'm happy to keep letting you know about these types of errors as I encounter them if you want.

**Comment by hozn** [comment]
Absolutely.  Now that I'm actively using stravalib again (I pick up
development in the winter for the freezingsaddles.com project), I do see
many of these myself and try to fix them, but very happy when people report
issues.  I hope to have the achievements error fixed in the next day or two.

**Comment by greenpasta** [comment]
I still get this one:

No such attribute similar_activities

**Comment by hozn** [comment]
Hmmmm ... this is using latest from git (or 0.4.0 release)?

**Comment by greenpasta** [comment]
Should be the latest:

stravalib==0.4.1dev

**Comment by hozn** [comment]
Yeah, looks right. Ok, I will dig into this

**Comment by marctc** [comment]
@hozn can you release a new version with these fixes?

**Comment by hozn** [comment]
Yeah, I can do that :)  -- Can you confirm that current master branch is
working ok?

**Comment by marctc** [comment]
I only tested get_activity, get_activity_stream and get_activities and it worked properly for  +100 different activities. The only thing that I saw was these warnings:

WARNING stravalib.model.ActivityLap-43 No such attribute device_watts on entity
WARNING stravalib.attributes.EntityCollection-223 Unable to set attribute device_watts on entity <SegmentEffort id=None name=None resource_state=2>

**Comment by hozn** [comment]
Ok, great.  Yeah, strava is constantly tweaking their responses (I guess
this is just a case of missing attribute).  I will get a new version
packaged up.

**Comment by hozn** [comment]
I rather quickly pushed up an 0.5.0; that *should* work.  I need to update
the published docs yet.  Probably need to do that this weekend.

**Comment by hozn** [comment]
This should be good; re-open if needed.

**Comment by marctc** [comment]
Thanks man!
