### ISSUE TITLE
get_activities results in AssertionError

### ISSUE THREAD

**Issue by maartenmennes** [hozn/stravalib#47]
upgrading from 0.3.0 to 0.4.0 broke get_activities. See the example below:

![image](https://cloud.githubusercontent.com/assets/1139180/6211517/1e5b2ef4-b5db-11e4-9e0d-8fe7c54a0558.png)

**Comment by hozn** [comment]
Ah, sorry; somehow I didn't encounter that issue.  Will fix asap.

**Comment by hozn** [comment]
Oh, wait; I didn't realize what you are doing. Yeah "after" should be a `datetime.datetime` value, not a `datetime.date` object.  This is because the value must be coerced to UTC and I don't believe `datetime.date` objects aren't tz-aware.

**Comment by maartenmennes** [comment]
ah great, that fixed it in 0.4.0. many thanks for the quick response!
