### ISSUE TITLE
get_activities only returns small set of activities

### ISSUE THREAD

**Issue by maartenmennes** [hozn/stravalib#49]
Hello,

For some reason a get_activities call only returns a fraction of my activities. I have about 500 activities in my account, stravalib is only returning 52 for the moment.

I say 'for some reason' as all was working fine 1-2 weeks ago. Updating to the latest stravalib (0.5.0) did not solve the problem.

Looking at the dates/numbers of the returned activities there seems to be no clear pattern in which ones it returned or did not return. I get recent as well as older activities.

**Comment by hozn** [comment]
Does it help to specify a (larger) limit value in your call to get_activities()?  In theory this should be abstracted using the paged results iterator, but perhaps something about API recently changed.  Maybe provide a small code sample of how you are currently retrieving the activities.

**Comment by maartenmennes** [comment]
Thanks for your reply! Below is an example of my get_activities() call.

![image](https://cloud.githubusercontent.com/assets/1139180/7319233/3dff880c-ea94-11e4-8e3e-3dc4f350c0b3.png)

As you can see, the initial call returns 52 items. Yet there should be 516. Restricting it by date seems to work, as it returns less data, a subset of the 52. This suggests that the problem is in the initial grabbing of activities.

**Comment by hozn** [comment]
Very detailed -- perfect.  I will take a look and try to reproduce myself.
It's hard to imagine that this is a new bug in stravalib, since that part
of the code hasn't changed recently to my recollection.  There must be
something that has changed in API or perhaps a bug in API (that wouldn't
surprise me either).  I will let you know what I find; thanks again.

**Comment by maartenmennes** [comment]
Great, thanks for looking into this. Just wanted to add verification that the subset is actually a subset of the activities that are also returned on the initial call.

![image](https://cloud.githubusercontent.com/assets/1139180/7319457/fd8828fe-ea95-11e4-99db-3f58d16193e8.png)

**Comment by maartenmennes** [comment]
Hello,

as I follow-up I just figured out it is returning only my public activities. That might narrow the search down to perhaps an authentication issue?

**Comment by maartenmennes** [comment]
Fixed it! I revoked access to my app, then asked for a new access_token (different from the one I already had), and things started working again. Is there an expiration date on those tokens?

**Comment by hozn** [comment]
Thanks for running it to ground.  I had this pinned in my inbox, but just
hadn't sat down to investigate.  I'm glad it works for you now.  (I wasn't
aware that the auth tokens expired, but good to know!)
