### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by greenpasta** [hozn/stravalib#60]
How does the rate limiting work in stravalib? A quick glance through the code makes me think it's on by default. I have a cron job that ran this morning at 3:15am and 6:15am and got the following error at 3:29am and 6:29am.

    requests.exceptions.HTTPError: 403 Client Error: Forbidden [Rate Limit Exceeded: [{'resource': 'Application', 'code': 'exceeded', 'field': 'rate limit'}]]

Both times it looks like it happened just before the rate limit would have rolled over. For now I've moved my job back to the 07 of the hour so I cross a rate limit reset sooner, and I could also introduce some delays into my script to help, but just thought I'd let you know that this happened.

**Comment by hozn** [comment]
It is possible the rules have changed; however, I believe this is *not* implemented by default (a quick glance at code suggests this is true).  You can pass in a rate limiter callable when you instantiate the Client class:

```python
from stravalib.util import limiter

client = Client(...., rate_limiter=limiter.DefaultRateLimiter)
```

Let me know if that fixes things for you.
