### ISSUE TITLE
athlete.all_ride_totals is empty

### ISSUE THREAD

**Issue by pbehrisch** [hozn/stravalib#61]
I tried the following code on python 2.7.10

```
from stravalib.client import Client
client = Client()
client.access_token = 'mytoken'
athlete = client.get_athlete()

dir(athlete)
['__abstractmethods__', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__metaclass__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_cache', '_abc_negative_cache', '_abc_negative_cache_version', '_abc_registry', '_followers', '_friends', 'agreed_to_terms', 'all_ride_totals', 'all_run_totals', 'approve_followers', 'assert_bind_client', 'badge_type_id', 'biggest_climb_elevation_gain', 'biggest_ride_distance', 'bikes', 'bind_client', 'city', 'clubs', 'country', 'created_at', 'date_preference', 'dateofbirth', 'description', 'deserialize', 'email', 'email_facebook_twitter_friend_joins', 'email_kom_lost', 'email_language', 'email_send_follower_notices', 'expand', 'facebook_sharing_enabled', 'firstname', 'follower', 'follower_count', 'follower_request_count', 'followers', 'friend', 'friend_count', 'friends', 'from_dict', 'ftp', 'global_privacy', 'id', 'instagram_username', 'lastname', 'log', 'max_heartrate', 'measurement_preference', 'mutual_friend_count', 'offer_in_app_payment', 'plan', 'premium', 'premium_expiration_date', 'profile', 'profile_medium', 'profile_original', 'receive_comment_emails', 'receive_follower_feed_emails', 'receive_kudos_emails', 'receive_newsletter', 'recent_ride_totals', 'recent_run_totals', 'resource_state', 'sample_race_distance', 'sample_race_time', 'sex', 'shoes', 'state', 'super_user', 'updated_at', 'username', 'weight', 'ytd_ride_totals', 'ytd_run_totals']

 print(athlete.all_ride_totals)
 None
```

Is that a bug or do I need to import another library here?

**Comment by hozn** [comment]
I suspect this might be an API change only reflected in master, but the all_ride_totals is actually part of the AthleteStats object now.

```
athlete = client.get_athlete()
athlete.stats.all_ride_totals
```

I intend to release an update that addresses this (and other) API changes, but you could clone master in near term.

**Comment by pbehrisch** [comment]
Thanks, that works. Do you know how to get unithelper to do the kilometer conversion so that the output is:  831.8 km?

       >>> print(athlete.stats.all_ride_totals.distance)
	831814.00 m
	>>> 831814.00 / 1000
	831.814
	>>> print unithelper.kilometers(athlete.stats.all_ride_totals.distance)
	831.00 km

**Comment by hozn** [comment]
This is odd; I do not know off-hand why it's truncating the values.  I will look into this.

**Comment by piotr-kubica** [comment]
It works in Python 3
`>>> from stravalib import Client
>>> from stravalib import unithelper
>>> athlete = client.get_athlete()
>>> print(unithelper.kilometers(athlete.stats.all_ride_totals.distance))
21179.63 km
>>> print(athlete.stats.all_ride_totals.distance)
21179632.00 m`

**Comment by hozn** [comment]
I'm going to assume this is a bug in units, as we're using python 3 division (`from __future__ import division ...`) and also not doing anything specifically for converting kilometers.
