### ISSUE TITLE
lots of warnings

### ISSUE THREAD

**Issue by maartenmennes** [hozn/stravalib#64]
Hello,

How would I avoid these warnings?

![image](https://cloud.githubusercontent.com/assets/1139180/12110701/50668c2e-b38f-11e5-8e6d-2fcd6369bcc4.png)

Thanks,
Maarten

**Comment by hozn** [comment]
I fixed this in master the other day. I'll roll a new 0.5.1 release soon.

**Comment by maartenmennes** [comment]
excellent! Just reinstalled from the github version and all those warnings have disappeared. Thank you so much!
