### ISSUE TITLE
Python 2.6 not supported

### ISSUE THREAD

**Issue by rosscado** [hozn/stravalib#65]
readme.md states the project's dependencies as "Python 2.6+" but importing stravalib in Python 2.6 gives an error.

    from stravalib.client import Client
    File "/usr/lib/python2.6/site-packages/stravalib/client.py", line 1071
    return {i.type: i for i in streams}
                        ^
    SyntaxError: invalid syntax

The following statement in client.py uses syntax new to Python 2.7:

    # Pack streams into dictionary
    return {i.type: i for i in streams}

The statement was introduced with revision 9f1385a2f50fd7111fb60374a47a1e036733ceea in Aug '14.

Can you please update stravalib's dependencies to Python 2.7+ or add Python 2.6 support?

**Comment by hozn** [comment]
Yeah, we will probability just drop 2.6 support at this point. Thanks for
noting!
