### ISSUE TITLE
Many Warnings generated

### ISSUE THREAD

**Issue by davew** [hozn/stravalib#68]
Hi,

I've installed using pip (seems I have version 0.5.0)

I get a heck of a lot of warnings generated and am wondering why eg

WARNING:stravalib.model.Athlete:No such attribute athlete_type on entity <Athlete id=8209 firstname=Dave lastname=Warnock>

WARNING:stravalib.model.Activity:No such attribute elev_low on entity <Activity id=None name=None resource_state=None>
WARNING:stravalib.model.Activity:No such attribute elev_high on entity <Activity id=504830637 name=None resource_state=None>
WARNING:stravalib.model.Activity:No such attribute total_photo_count on entity <Activity id=504830637 name=None resource_state=None>
WARNING:stravalib.model.Activity:No such attribute suffer_score on entity <Activity id=504830637 name=u'WORK: Evening service ' resource_state=None>

Is this due to Strava API changes or what?

**Comment by hozn** [comment]
Yes, this is due to Strava API changes.  I've been remiss in pushing out a
new version, but these should all be fixed in the latest (master) branch.
I'll push out a new release when I have a minute to type up some release
notes.

**Comment by davew** [comment]
Thanks Hans.

I'll switch to the master branch.
