### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by davew** [hozn/stravalib#69]
What is the current status of the master branch regarding Python 3?

Thanks

**Comment by hozn** [comment]
I've heard of people using it (I believe the setup.py still has 2to3=True), but I've only worked with it in python 2.  As I mentioned in #70, I'd like to use [six](https://pypi.python.org/pypi/six/) to build code that works in both 2 and 3.

**Comment by davew** [comment]
Thanks for this!

**Comment by hozn** [comment]
Sorry it took so long to get around to it! The real job has been keeping me
too busy.
