### ISSUE TITLE
Webhook Events Support

### ISSUE THREAD

**Issue by loisaidasam** [hozn/stravalib#77]
Would be cool to see support for Webhook Events:

http://strava.github.io/api/partner/v3/events/

**Comment by hozn** [comment]
Sure, pull requests welcome!

**Comment by loisaidasam** [comment]
Sweet, looking into it now :)

**Comment by hozn** [comment]
Thank you!

**Comment by hozn** [comment]
Initial commit merged, thank you!  Still outstanding here:
- Remainder of API
- Tests
- Updated user docs

**Comment by hozn** [comment]
Ok, I think this is done.  @loisaidasam maybe you can test out the list/del endpoint when you get this working on your end.  (My app/API key won't get push notifications.)  Date handling should be much improved now with Arrow so sub update event_time will be handled correctly as date.

**Comment by loisaidasam** [comment]
Busy weekend! Nice work. Will definitely test out the list/del endpoints for you. Thanks for the urgency with bringing this functionality in, much appreciated 👍

**Comment by loisaidasam** [comment]
Just tested, and I can confirm that all create, list, and delete functionality do indeed work! 👍

**Comment by hozn** [comment]
Thank you, sir!
