### ISSUE TITLE
Better Explanation of Attribute `resource_states`

### ISSUE THREAD

**Issue by loisaidasam** [hozn/stravalib#78]
Unless I'm missing something, it's a bit vague what these Attribute `resource_states` mean or how they are used:

https://github.com/hozn/stravalib/blob/0f760a163856c2ec4262d3f21407b53456c087a6/stravalib/attributes.py#L17-L19

I think some comments around the variable declarations might go a long way.

**Comment by hozn** [comment]
True.  They aren't actually being enforced anywhere, so it's more informational.  They match up to the resource states defined by Strava, from https://strava.github.io/api/ :
```
Object representations
Depending on the type of request, objects will be returned in meta,  summary or detailed representations. The representation of the returned object is indicated by the resource_state attribute.

Resource states
1	meta
2	summary
3	detailed
Listed in increasing levels of detail.
```
