### ISSUE TITLE
Create a tag for version 0.6.0

### ISSUE THREAD

**Issue by Tafkas** [hozn/stravalib#81]
In https://github.com/hozn/stravalib/blob/master/setup.py#L9 it says current version is 0.6.0 while the last tag points to version 0.5.0. Also on PyPi the latest version is 0.5.0. Since there were some useful changes made afterwards  (e.g. athlete_type on the Athlete model)  it would be awesome if there was a new release.

**Comment by hozn** [comment]
Yeah, have been meaning to do this.  It's now tagged and release to pypi.
