### ISSUE TITLE
delete_activity missing?

### ISSUE THREAD

**Issue by nall** [hozn/stravalib#85]
I'd like to delete some activities, but I don't see an API for that. Am I missing something or is it not implemented yet?

**Comment by hozn** [comment]
Indeed! -- Apparently this is missing.  I'll add it in.

https://strava.github.io/api/v3/activities/#delete

In the short-term, you can work around this lack using the protocol method attached to the Client:

```python
# client = Client() .. etc.
client.protocol.delete('/activities/{id}', id=activity_id)
```

Hope that helps most immediately and thanks for pointing out the oversight.  I guess not many have actually gone to delete activities.

**Comment by nall** [comment]
Yep that was my exact workaround. Thanks for the quick add!

**Comment by hozn** [comment]
I also went ahead and added `client.delete_activity()` method in master branch. This is not tested yet (we're still lacking a good functional testing framework unfortunately).
