### ISSUE TITLE
Support: Easiest way of getting activities or segments of a 'friend/follower'

### ISSUE THREAD

**Issue by mpschr** [hozn/stravalib#88]
Hi

I am exploring the possibilities of stravalib and the Strava API. what would be the easiest way for obtaining the activities of a certain (user-provided) friend who is followed by me and vice-versa?

Thanks for pointing me into the right direction
Best,
mpschr

**Comment by hozn** [comment]
Sure, you want to use the `client.get_friend_activities()` method.  https://github.com/hozn/stravalib/blob/master/stravalib/client.py#L481
