### ISSUE TITLE
Set access_scope

### ISSUE THREAD

**Issue by greenpasta** [hozn/stravalib#89]
Is it possible to set the access scope within stravalib?

For example, I am doing:

client = Client(access_token='MYACCESSTOKEN')
activities = client.get_activities()

I want this to also find private activities, so I think I need to set the scope to 'view_private', but I don't know how/where.

**Comment by hozn** [comment]
Yeah, you can do this; you need to specify the scope in the authorization URL.  Here's a (Flask) snippet:

```python
@blueprint.route("/authorize")
def join():
    c = Client()
    public_url = c.authorization_url(client_id=app.config['STRAVA_CLIENT_ID'],
                                     redirect_uri=url_for('.authorization', _external=True),
                                     approval_prompt='auto')
    private_url = c.authorization_url(client_id=app.config['STRAVA_CLIENT_ID'],
                                      redirect_uri=url_for('.authorization', _external=True),
                                      approval_prompt='auto',
                                      scope='view_private')    # <--  Here's the important bit!
    return render_template('authorize.html', public_authorize_url=public_url, private_authorize_url=private_url)
```

And just for completeness, here is a simplified version of my callback URL handler (aka "view"):

```python
@blueprint.route("/authorization")
def authorization():
    """
    Method called by Strava (redirect) that includes parameters.
    - state
    - code
    - error
    """
    error = request.args.get('error')
    state = request.args.get('state')
    if error:
        return render_template('authorization_error.html', error=error)
    else:
        code = request.args.get('code')
        client = Client()
        access_token = client.exchange_code_for_token(client_id=app.config['STRAVA_CLIENT_ID'],
                                                      client_secret=app.config['STRAVA_CLIENT_SECRET'],
                                                      code=code)
        # Now store token
```

**Comment by greenpasta** [comment]
Thanks for the reply, I've been away for a while.

I'm not using Flask (or any framework), I'm just using Stravalib in a python shell script. I'm not doing any of the "authorization_url" stuff you mentioned. Any chance I could see the authorize.html template so I can try to put these pieces together? I need to see how you are getting the code that you are exchanging for access_token.

**Comment by hozn** [comment]
Hope I can help -- the authorize.html that I was probably referencing would be this one: https://github.com/hozn/freezingsaddles/blob/master/bafs/templates/authorize.html  -- but the important point is that the user, logged-in to Strava in web browser, has to navigate to a URL that will ask them whether they would like to give the application ability to read data (maybe including private).

If you are just doing this yourself, you can construct your own URL to paste into the web browser using something like:
```python
private_url = c.authorization_url(client_id=app.config['STRAVA_CLIENT_ID'],
                                      redirect_uri='http://localhost:8000/',
                                      approval_prompt='auto',
                                      scope='view_private')    # <--  Here's the important bit!
```

The redirect_uri is going to need to be set to a server you have running (e.g. on localhost) that will take the code and exchange it for a token (that is my {{/authorization}} example above).  Hope that is clear.

More here: https://strava.github.io/api/v3/oauth/

**Comment by greenpasta** [comment]
That helps, I should be able to get it going. Thanks!
