### ISSUE TITLE
update_activity doesn't update the description field

### ISSUE THREAD

**Issue by sanderroosendaal** [hozn/stravalib#91]
The activity_type came through, but the description wasn't copied. Looking at stravalib source code, in "update_activity", I don't see the part where you actually set the description. Here is the code I am looking at:

# Convert the kwargs into a params dict
        params = dict(activity_id=activity_id)
        if name is not None:
            params['name'] = name
        if activity_type is not None:
            if not activity_type.lower() in [t.lower() for t in model.Activity.TYPES]:
                raise ValueError("Invalid activity type: {0}.  Possible values: {1!r}".format(activity_type, model.Activity.TYPES))
            params['type'] = activity_type
        if private is not None:
            params['private'] = int(private)
        if commute is not None:
            params['commute'] = int(commute)
        if trainer is not None:
            params['trainer'] = int(trainer)
        if gear_id is not None:
            params['gear_id'] = gear_id

        raw_activity = self.protocol.put('/activities/{activity_id}', **params)

**Comment by hozn** [comment]
Thanks for pointing this out.  Pushed this out in 0.6.3.
