### ISSUE TITLE
Beginner's issue: code = request.get('code')

### ISSUE THREAD

**Issue by intuitionofmind** [hozn/stravalib#93]
Hi,
I just start to use this lib under the instruction by README.md. I follow all the procedures and try to access my account on Strava. My script is here:
```
#!/usr/bin/python                                                                                                                      
   
from stravalib.client import Client
# import request
# import requests
   
client = Client()
authorize_url = client.authorization_url(client_id=3923875, redirect_uri='http://localhost:8282/authorized')
 
code = request.get('code')
access_token = client.exchange_code_for_token(client_id=3923875, client_secret='*************', code=code) 
```
It tells me that **NameError: name 'request' is not defined**. I have tried to import module 'request' as commented, but it also tells me that **AttributeError: module 'request' has no attribute 'get'**. I have also tried to import module 'requests' but it did not work either. Any one could help me?

**Comment by jsamoocha** [comment]
Hi,

the example in the README is not meant to be run as a script. Instead the authentication procedure should be (roughly) as follows:

1. Somehow, in some web application, a user should be able to click on a link referring to the url generated by `client.authorization_url()`. Alternatively (as a very premature testing setup), you could type that url in your browser,
2. Strava will now process the authentication and redirect your browser to the `redirect_uri` you provided as argument to `client.authorization_url()`,
3. This redirect will have `code` as HTTP request parameter, which is added by Strava,
4. You need to provide some endpoint that can process this request, and retrieve the `code` parameter from it,
5. This endpoint can then exchange the temporary code with a permanent access token by using the `client.exchange_code_for_token()` convenience method;

[This additional documentation by Strava](http://strava.github.io/api/v3/oauth/) may help better understand the authentication process. You may need to catch up on some understanding of web applications or endpoints, in the Python world you usually end up at Flask or Django.

Hope this helps, cheers!

**Comment by hozn** [comment]
@jsamoocha , thanks for answering this question!

**Comment by intuitionofmind** [comment]
@jsamoocha Thank you very much. I really appreciate your patient answer.
