### ISSUE TITLE
photos endpoint is missing an argument

### ISSUE THREAD

**Issue by nall** [hozn/stravalib#94]
When invoking `get_activity_photos`, the library should append `photo_sources=true` to the request per [this documentation](https://strava.github.io/api/v3/activity_photos/#list).

Without it I get an empty list. With it, I get the expected photos.

**Comment by hozn** [comment]
Thanks for pointing this out!

**Comment by hozn** [comment]
@nall , just a heads up that in 0.6.5 I changed the get_activity_photos behavior to behave like it used to (only returning Instagram);  you can pass only_instagram=False to get both.  (I also needed to fix  `ActivityPhoto` to handle the native photos, and I figured this was too much a breaking change to suprise users in a point release.)

There is also a new `size` param, which is probably useful here.

**Comment by nall** [comment]
Thanks for the heads up!
