### ISSUE TITLE
"laps" attribute was removed from Activity

### ISSUE THREAD

**Issue by ollyajoke** [hozn/stravalib#96]
When trying to access an activity I got an error like:
Could not find attribute `laps` on entity <Activity id=... > (Original: AttributeError("can't set attribute",))

Simply commenting out the `laps` attribute (https://gist.github.com/ollyajoke/13d8656a380d70d846fc8fffff9a40fc) fixed the issue for me for now.

**Comment by GroveJay** [comment]
I dealt with this last night. The base activity api call now returns the lap information as a list. When deserializing and setting the Activity attributes, the exception is thrown as "Activity.laps" already exists (what you commented out). The existing property is written to use the [laps api](https://strava.github.io/api/v3/activities/#laps).

In summary:
- Strava is adding ([undocumented!](https://strava.github.io/api/v3/activities/)) data to their api call
- Stravalib does not ignore this extra data and throws an exception adding it to the Activity model

Possible fixes:
- Ignore the extra data
  - This can be a one-line fix (add `and k != laps` [here](https://github.com/hozn/stravalib/blob/master/stravalib/model.py#L43)), but that is ugly and has side effects. Realistically, deserialization should not be done blindly.
- Add the new data to the model
  - The existing laps property would need to be renamed
  - Coexistence of both laps properties would need to be thought through.

**Comment by woodmicha** [comment]
I encountered the same problem and was assuming something on my end was goofed.  Is it correct to say the problem is the Strava REST web app just started returning laps for Activities or did the client bindings change?  Reason I ask is I was upgrading my libraries when I encountered the issue.

**Comment by ebrensi** [comment]
This happens with `Client.get_activity()` but not with `Client.get_activities()`.

**Comment by GroveJay** [comment]
@woodmicha Correct, I don't believe this is because of anything updated with stravalib. The last commit for stravalib was on [10/26](https://github.com/hozn/stravalib/commit/c763a39bcd94306c3b385bb128741699f60cb912) from pr #95.

**Comment by GroveJay** [comment]
@ebrensi that's a good data point. The data being returned in the [/athlete/activities](https://github.com/hozn/stravalib/blob/master/stravalib/client.py#L187) api call is different than the [/activities/{id}](https://github.com/hozn/stravalib/blob/master/stravalib/client.py#L477) call (/athlete/activities has 13 less properties), and does not have the 'laps' data.

For completeness:
The additional properties /activities/{id} returns are:
- partner_brand_tag
- best_efforts
- splits_standard
- segment_efforts
- calories
- partner_logo_url
- laps
- splits_metric
- similar_activities
- embed_token
- photos
- description
- device_name

This is described in the [api docs](https://strava.github.io/api/v3/activities/#summary-representation-attributes-a-idsummarynbspa), but not completely. `gear_id` is returned in the summary view and the undocumented properties below are returned in the detailed /activities/{id} view:

- partner_brand_tag
- partner_logo_url
- laps
- similar_activities

**Comment by hozn** [comment]
Interesting ... I guess we need to support the new laps data and rename the current laps api call.  There is some precedent for this happening with photos API too.  It is an API breaking change, so I will bump at least the minor version (should probably adopt semantic versioning here) and make it explicit in changelog.

**Comment by hozn** [comment]
So, after a bit more investigation, it would appear that the laps data returned with the activity detail is the same as the array.  So I'm just going to make the laps property settable; that seems to do the trick.

**Comment by hozn** [comment]
FYI -- pushed this out in 0.6.4.  Let me know if any issues discovered.

**Comment by ebrensi** [comment]
Thanks!
